---
title: "RWorksheet_Sabarillo#2"
author: "Sabarillo, Kirk Axl Dend"
date: "2024-09-30"
output: html_document
---

1.a
```{r}
operator <- -5:5
operator

#1.b

x <- 1:7
x
```
2.
```{r}
seq(1, 3, by=0.2)
```
3.
```{r}
ages <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27,
          22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 43, 53, 41, 51, 35,
          24, 33, 41, 53, 40, 18, 44, 38, 41, 48, 27, 39, 19, 30, 61, 54, 58, 26,
          18)

#3.a - the 3rd element is 22

age_3 <- ages[3]

age_3

#3.b - 2nd and 4th element values are 28 and 36

secondfourth <- ages[c(2, 4)]

secondfourth

#3.c

allbut4and12 <- ages[-c(4, 12)]

allbut4and12
```
4.
```{r}
#4.a -  The first output shows the entire vector with its names. The second output shows only the elements specified by the names "first" and "third." This demonstrates how to access elements of a named vector using their names.

x <- c("first"=3, "second"=0, "third"=9)

names(x) <- c("first", "second", "third")

#4.b

x

(x[c("first", "third")])
```
5.
```{r}
#5.a - The output shows the modified sequence with the 2nd element replaced by 0
x <- -3:2

x[2] <- 0

#5.b

x
```
6.
```{r}
#6.a
month <- c("Jan", "Feb", "March", "Apr", "May", "June")
ppl <- c(52.50, 57.25, 60.00, 65.00, 74.25, 54.00)
pq <- c(25, 30, 40, 50, 10, 45)

df <- data.frame(month, ppl, pq)
  
df

#6.b - The output will show the average fuel expenditure of Mr. Cruz from January to June.

afe <- weighted.mean(ppl, pq)

afe
```
7.
```{r}
#7.a
data <- c(length(rivers), sum(rivers), mean(rivers), median(rivers), var(rivers),
          sd(rivers), min(rivers), max(rivers))
#7.b - The output will display the calculated values for the rivers dataset.
# 141.0000  83357.0000    591.1844    425.0000 243908.4086    493.8708    135.0000   3710.0000

#7.c

data
```
8.
```{r}
#8.a

pr <- c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25)
celebrity <- c("Tom Cruise", "Rolling Stones", "Oprah Winfrey", "U2", "Tiger Woods", "Steven Spielberg", "Howard Stern", "50 Cent", "Cast of the Sopranos", "Dan Brown", "Bruce Sprinsteen", "Donal Trump", "Muhammad Ali", "Paul McCartney", "George Lucas", "Elton John", "David Letterman", "Phil Mickelson", "J.K. Rowling", "Brad Pitt", "Peter Jackson", "Dr. Phil McGraw", "Jay Leno", "Celine Dion", "Kobe Bryant")
pay <- c(67, 90, 225, 110, 90, 332, 302, 41, 52, 88, 55, 44, 55, 40, 233, 60, 40, 47, 75, 25, 39, 45, 32, 40, 31)
pr
celebrity
pay
#8.b

Change <- which(celebrity == "J.K. Rowling")
pr[Change] <- 15
pay[Change] <- 90

#8.c
Forbesranks <- read.csv("/cloud/project/Worksheet-2/PowerRanking.csv")

#8.d
Ranks <- Forbesranks[10:20,]
Ranks
save(Ranks, file = "/cloud/project/Ranks.RData")

#8.e: the output prints the rows from 10 to 20.

```
9.
```{r}
#9.A
library("openxlsx")
library("readxl")
hotelsvienna <- read_xlsx("/cloud/project/Worksheet-2/hotels-vienna.xlsx")

#9.)b: It has 428 row dimensions and 24 column dimensions

dim(hotelsvienna)

#9.c
column <- hotelsvienna[, c("country", "neighbourhood", "price","stars", "accommodation_type", "rating")]

#9.d
save(column, file ="/cloud/project/new.RData")

#9.e
load("/cloud/project/new.RData")
head(column, 6)
tail(column, 6)
```
10.
```{r}
#10.a
vegetables <- list("Potato", "Carrot", "Onion", "Spinach", "Cabbage", "Eggplant", "Tomato", "Lettuce", "Radish", "Garlic")
vegetables

#10.b
vegetables <- append(vegetables, list("Cucumber", "Squash"))
vegetables

#10.c - 16 data points
vegetables <- append(vegetables, list("Cauliflower", "Asparagus", "Green Beans", "Beet Root"))
vegetables
length(vegetables)

#10.d - 13 vegetables were left
vegetables <- vegetables[-c(5, 10, 15)]
vegetables
```




