---
title: "RWorksheet_Sabarillo#3b"
author: "Sabarillo, Kirk Axl Dend"
date: "2024-10-13"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#1.a
maketable <- data.frame(Respondent = c(1:20),Sex = c(2,2,1,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,1,2),FathersOccupation = c(1,3,3,3,1,2,3,1,1,1,3,2,1,3,3,1,3,1,2,1),PersonsAtHome = c(5,7,3,8,5,9,6,7,8,4,7,5,4,7,8,8,3,11,7,6),SiblingsatSchool = c(6,4,4,1,2,1,5,3,1,2,3,2,5,5,2,1,2,5,3,2),TypesOfHouses = c(1,2,3,1,1,3,3,1,2,3,2,3,2,2,3,3,3,3,3,2))
maketable
```
#Legend:Male=1      Farmer=1    Wood=1
#       Female=2    Driver=2    Semi-Concrete=2 
#                   Others=3    Concrete=3
```{r}
#1.b
summary(maketable)
#1.c: No, the mean is 2.95 based on summary
```

```{r}
#1.d
access <- maketable[1:2,]
access
```

```{r}
#1.e
access2 <- maketable[c(3,5),c(2,4)]
access2
```

```{r}
#1.f
typeshouses <- maketable$TypesOfHouses
typeshouses
```

```{r}
#1.g
malesrespondent <- subset(maketable, Sex == 1 & FathersOccupation == 1)
malesrespondent
```

```{r}
#1.h
femrespondent <- subset(maketable, Sex == 2 & SiblingsatSchool >= 5)
femrespondent
```

```{r}
#2
df = data.frame(Ints=integer(),

Doubles=double(), Characters=character(),
Logicals=logical(),
Factors=factor(),
stringsAsFactors=FALSE)

print("Structure of the empty dataframe:")
print(str(df))

#2.a: It prints the datatype of the object and there's 0 levels
```

```{r}
#3.a
HousesData <- read.csv("/cloud/project/worksheet#3/HouseholdData.csv")
HousesData
```

```{r}
#3.b
HousesData$Sex <- factor(HousesData$Sex, levels = c("Male", "Female"), labels = c(1,2))
HousesData
```

```{r}
#3.c
HousesData$Types.of.Houses <- factor(HousesData$Types.of.Houses, levels = c("Wood", "Congrete", "Semi-Congrete"), labels = c(1,2,3))
HousesData
```

```{r}
#3.d
HousesData$Fathers.Occupation <- factor(HousesData$Fathers.Occupation, levels = c(1,2,3), label = c("Farmer", "Driver", "Others"))
HousesData  
```

```{r}
#3.e
DriverDad <- subset(HousesData, Sex == 2 & Fathers.Occupation == "Driver")
DriverDad
```

```{r}
#3.f
siblings <- subset(HousesData, Respondents & Siblings.at.School >= 5)
siblings
```

```{r}
#4
#. The graph illustrates the daily sentiment of tweets over a week in July.  It reveals a consistent trend where negative tweets were the most prevalent throughout the period, followed by positive tweets.  Neutral tweets remained the least common and showed a steady, unchanging volume each day. This suggests a generally negative conversation on Twitter during this time, with a consistent underlying level of neutral commentary
```